version: 2.1

jobs:
  terraform:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init
      - run:
          name: Plan Terraform Changes
          command: terraform plan -out=tfplan
      - run:
          name: Apply Terraform Changes
          command: terraform apply -auto-approve tfplan

workflows:
  version: 2
  build:
    jobs:
      - terraform
